version: '3'
services:


  db:
    restart: always
    image: mysql
    build:
      context: /usr/local/credit-facility
    ports:
      - 3306:3306/tcp
    volumes:
      - "credit-facility-volume:/var/lib/mysql:rw"
    environment:
      - MYSQL_DATABASE=db_credit_facility
      - MYSQL_ROOT_PASSWORD=evan123
    networks:
      - demo-overlay
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  credit-facility-service:
    restart: always
    image: credit-facility-image
    build:
      context: /usr/local/credit-facility
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=evan123
      - DB_NAME=db_credit_facility
    networks:
      - demo-overlay
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s


  nginx:
    restart: always
    depends_on:
      - db
      - credit-facility-service
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /usr/local/credit-facility/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - demo-overlay
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager



networks:
  demo-overlay:
    driver: overlay


volumes:
  credit-facility-volume: {}