server:
  port: 9003
spring:
  application:
    name: server-consumer
  cloud:
    consul:
      host: 192.168.99.105
      port: 8500
      discovery:
        health-check-interval: 10s
        service-name: ${spring.application.name}
        register-health-check: true
        health-check-path: /check
        register: false